### ISSUE TITLE
Injection of userId on sync.where

### ISSUE THREAD

**Issue by jonbomme** [mesqueeb/VuexEasyFirestore#23]
Hi 

It would be really usable if one have userId injected onto a sync.where configuration like:

```
sync: {
    where: [['users', 'array-contains', '{userId}']]
  } 
```

Best regards,
Jon

**Comment by mesqueeb** [comment]
Dear Jon. 
Thanks for your issue!

I believe it’s possible even now! Just pass the user id as third argument. Doesn’t it work?

I will also do some more tests next week. Keep you posted.

**Comment by mesqueeb** [comment]
Oh wait I see. You don’t know the `userId` at the time of the settings!

I didn’t have this problem before because I only used the userid in the syncPath myself, not in the where. 

So I will make this a possibility this weekend and let you know.

In the meantime I would wanna ask if this doesn’t cause you any security issues on your side? I think this way it's possible for users to edit other user's documents or to even retrieve all docs of all users. How did you set up your security rules in your case? 

I have also not yet used 'array-contains' myself, so i'll research that.

**Comment by rchan** [comment]
I have the same issue, although I'm only doing '==' rather than 'array-contains'

We can't have the documents separated under each user because we have an admin side of the app that needs to work on the documents as a single collection

the rule for '==' would be (from example in docs https://firebase.google.com/docs/firestore/security/rules-query), think dealing with 'array-contains' is also possible

```
service cloud.firestore {
  match /databases/{database}/documents {
    match /stories/{storyid} {
      // Only the authenticated user who authored the document can read or write
      allow read, write: if request.auth.uid == resource.data.author;
    }
  }
}
```

**Comment by mesqueeb** [comment]
@rchan @jonbomme I just pushed version 1.7 which will automatically replace `'{userId}'` with the actual `userId` at the time you do `dispatch('openDBChannel')`. Make sure that you add `'{userId}'` just like that as third param of the where filter in `sync.where`.

Can you update with npm and let me know how it goes?

Let me know if there are any problems or bugs or feel free to open a new issue with other requests!

**Comment by mesqueeb** [comment]
@rchan I'm assuming you retrieve the variables after the user has logged in?

I'm currently writing compatibility for any `arbitrary variable`. Please hold ons.

**Comment by mesqueeb** [comment]
@rchan 
I have made this possible through custom variables passed as parameter like so: `dispatch('module/openDBChannel', {customVar: customId})`.

Please update to `npm i vuex-easy-firestore@1.9.0`
and check the new documentation [here](https://github.com/mesqueeb/VuexEasyFirestore#variables-for-firestorepath-or-filters).

Feel free to write additional feedback or comments, or if all good please close this issue!

**Comment by jonbomme** [comment]
Cool! I will try it out later!

**Comment by rchan** [comment]
no time to try it out at the moment, but API wise it would be what I want
